import { type ClientSchema, a, defineData } from "@aws-amplify/backend";

const schema = a.schema({
  // User Profile - extends Cognito user with additional fields
  UserProfile: a
    .model({
      userId: a.string().required(), // Cognito user sub
      email: a.string().required(),
      name: a.string(),
      profilePicture: a.string(),
      agoraUsername: a.string(), // Username displayed in Agora calls
      organizationId: a.id(),
      role: a.enum(["PROJECT_MANAGER", "EMPLOYEE"]),
      organization: a.belongsTo("Organization", "organizationId"),
      createdAt: a.datetime(),
      updatedAt: a.datetime(),
    })
    .authorization((allow) => [
      allow.authenticated(),
      allow.owner().to(["read", "update"]),
    ]),

  // Organization - created by project managers
  Organization: a
    .model({
      name: a.string().required(),
      ownerId: a.string().required(), // Cognito user sub of creator
      members: a.hasMany("UserProfile", "organizationId"),
      invites: a.hasMany("OrganizationInvite", "organizationId"),
      meetings: a.hasMany("Meeting", "organizationId"),
      tasks: a.hasMany("Task", "organizationId"),
      tickets: a.hasMany("Ticket", "organizationId"),
      createdAt: a.datetime(),
      updatedAt: a.datetime(),
    })
    .authorization((allow) => [allow.authenticated()]),

  // Organization Invites
  OrganizationInvite: a
    .model({
      organizationId: a.id().required(),
      organization: a.belongsTo("Organization", "organizationId"),
      email: a.string().required(),
      status: a.enum(["PENDING", "ACCEPTED", "REJECTED"]),
      invitedBy: a.string().required(), // Cognito user sub
      createdAt: a.datetime(),
      expiresAt: a.datetime(),
    })
    .authorization((allow) => [allow.authenticated()]),

  // Meeting
  Meeting: a
    .model({
      organizationId: a.id().required(),
      organization: a.belongsTo("Organization", "organizationId"),
      title: a.string().required(),
      channelName: a.string().required(), // Agora channel name
      status: a.enum(["SCHEDULED", "LIVE", "COMPLETED", "CANCELLED"]),
      startedAt: a.datetime(),
      endedAt: a.datetime(),
      createdBy: a.string().required(), // Cognito user sub
      participants: a.string().array(), // Array of user IDs
      transcripts: a.hasMany("Transcript", "meetingId"),
      tasksCreated: a.hasMany("Task", "meetingId"),
      recordingUrl: a.string(),
      createdAt: a.datetime(),
      updatedAt: a.datetime(),
    })
    .authorization((allow) => [allow.authenticated()]),

  // Transcript - real-time speech-to-text from Agora
  Transcript: a
    .model({
      meetingId: a.id().required(),
      meeting: a.belongsTo("Meeting", "meetingId"),
      userId: a.string().required(), // Who spoke
      userName: a.string(),
      text: a.string().required(),
      timestamp: a.datetime().required(),
      confidence: a.float(), // STT confidence score
      processed: a.boolean().default(false), // Whether AI has analyzed for tasks
      createdAt: a.datetime(),
    })
    .authorization((allow) => [allow.authenticated()]),

  // Task - created manually or auto-generated from meeting AI
  Task: a
    .model({
      organizationId: a.id().required(),
      organization: a.belongsTo("Organization", "organizationId"),
      meetingId: a.id(),
      meeting: a.belongsTo("Meeting", "meetingId"),
      title: a.string().required(),
      description: a.string(),
      assignedTo: a.string(), // Cognito user sub
      assignedBy: a.string().required(), // Cognito user sub
      status: a.enum(["TODO", "IN_PROGRESS", "IN_REVIEW", "COMPLETED", "BLOCKED"]),
      priority: a.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]),
      dueDate: a.date(),
      tags: a.string().array(),
      autoGenerated: a.boolean().default(false), // True if created by AI
      transcriptReference: a.id(), // Links to transcript that generated this
      tickets: a.hasMany("Ticket", "taskId"),
      createdAt: a.datetime(),
      updatedAt: a.datetime(),
      completedAt: a.datetime(),
    })
    .authorization((allow) => [allow.authenticated()]),

  // Ticket - employee requests to project manager
  Ticket: a
    .model({
      organizationId: a.id().required(),
      organization: a.belongsTo("Organization", "organizationId"),
      taskId: a.id().required(),
      task: a.belongsTo("Task", "taskId"),
      type: a.enum(["DEADLINE_EXTENSION", "RESOURCE_REQUEST", "CLARIFICATION", "BLOCKER", "OTHER"]),
      subject: a.string().required(),
      description: a.string().required(),
      createdBy: a.string().required(), // Employee user sub
      assignedTo: a.string(), // PM user sub (defaults to task creator)
      status: a.enum(["OPEN", "IN_REVIEW", "RESOLVED", "REJECTED"]),
      resolution: a.string(),
      priority: a.enum(["LOW", "MEDIUM", "HIGH"]),
      createdAt: a.datetime(),
      updatedAt: a.datetime(),
      resolvedAt: a.datetime(),
    })
    .authorization((allow) => [allow.authenticated()]),
});

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "userPool",
  },
});

/*== STEP 2 ===============================================================
Go to your frontend source code. From your client-side code, generate a
Data client to make CRUDL requests to your table. (THIS SNIPPET WILL ONLY
WORK IN THE FRONTEND CODE FILE.)

Using JavaScript or Next.js React Server Components, Middleware, Server 
Actions or Pages Router? Review how to generate Data clients for those use
cases: https://docs.amplify.aws/gen2/build-a-backend/data/connect-to-API/
=========================================================================*/

/*
"use client"
import { generateClient } from "aws-amplify/data";
import type { Schema } from "@/amplify/data/resource";

const client = generateClient<Schema>() // use this Data client for CRUDL requests
*/

/*== STEP 3 ===============================================================
Fetch records from the database and use them in your frontend component.
(THIS SNIPPET WILL ONLY WORK IN THE FRONTEND CODE FILE.)
=========================================================================*/

/* For example, in a React component, you can use this snippet in your
  function's RETURN statement */
// const { data: todos } = await client.models.Todo.list()

// return <ul>{todos.map(todo => <li key={todo.id}>{todo.content}</li>)}</ul>
