import { Badge } from "@/components/ui/badge"
import { Calendar, Sparkles, AlertCircle } from "lucide-react"
import { cn } from "@/lib/utils"
import { useAuth } from "@/lib/auth-context"
import { CreateTicketDialog } from "@/components/create-ticket-dialog"

import { Task } from '@/lib/types';

interface TaskCardProps {
  task: Task;
  isDragging?: boolean
  onUpdate?: () => void
}

const priorityColors = {
  LOW: "bg-blue-500/10 text-blue-500",
  MEDIUM: "bg-yellow-500/10 text-yellow-500",
  HIGH: "bg-orange-500/10 text-orange-500",
  URGENT: "bg-red-500/10 text-red-500",
}

export function TaskCard({ task, isDragging, onUpdate }: TaskCardProps) {
  const { user } = useAuth()
  
  const formattedDate = task.dueDate 
    ? new Date(task.dueDate).toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
      })
    : "No date"

  const isAssignedToMe = task.assignedTo === user?.userId
  const isCreatedByMe = task.assignedBy === user?.userId

  return (
    <div
      className={cn(
        "rounded-xl bg-card p-3 sm:p-4 shadow-sm border border-border transition-shadow",
        isDragging ? "shadow-lg ring-2 ring-primary/20" : "hover:shadow-md",
      )}
    >
      <div className="space-y-3">
        {/* Header */}
        <div className="flex items-start justify-between gap-2">
          <h4 className="text-xs sm:text-sm font-medium text-foreground leading-snug flex-1 min-w-0">
            {task.title}
          </h4>
          {task.autoGenerated && (
            <span title="AI Generated">
              <Sparkles className="h-3.5 w-3.5 text-purple-500 flex-shrink-0" />
            </span>
          )}
        </div>

        {/* Description */}
        {task.description && (
          <p className="text-xs text-muted-foreground line-clamp-2">
            {task.description}
          </p>
        )}

        {/* Tags */}
        {task.tags && task.tags.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {task.tags.filter((tag): tag is string => tag !== null && tag !== undefined).slice(0, 3).map((tag: string) => (
              <Badge key={tag} variant="secondary" className="text-xs px-1.5 py-0">
                {tag}
              </Badge>
            ))}
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center justify-between gap-2 pt-2 border-t border-border">
          <div className="flex items-center gap-2">
            {task.priority && (
              <Badge className={cn("text-xs", priorityColors[task.priority as keyof typeof priorityColors])}>
                {task.priority}
              </Badge>
            )}
            {task.dueDate && (
              <div className="flex items-center gap-1 text-xs text-muted-foreground">
                <Calendar className="h-3 w-3" />
                <span>{formattedDate}</span>
              </div>
            )}
          </div>

          {/* Ticket button for assigned users */}
          {isAssignedToMe && !isCreatedByMe && (
            <CreateTicketDialog
              taskId={task.id}
              taskTitle={task.title}
              assignedBy={task.assignedBy}
              onTicketCreated={onUpdate}
            >
              <button className="text-xs text-muted-foreground hover:text-foreground transition-colors">
                <AlertCircle className="h-3.5 w-3.5" />
              </button>
            </CreateTicketDialog>
          )}
        </div>
      </div>
    </div>
  )
}

