import type { User, Task, Meeting, TeamActivity } from "./types"

export const currentUser: User = {
  id: "1",
  name: "Sarah Chen",
  email: "sarah@company.com",
  avatar: "/professional-woman-avatar.png",
  role: "manager",
}

export const teamMembers: User[] = [
  currentUser,
  {
    id: "2",
    name: "Alex Rivera",
    email: "alex@company.com",
    avatar: "/professional-man-avatar.png",
    role: "member",
  },
  {
    id: "3",
    name: "Jordan Kim",
    email: "jordan@company.com",
    avatar: "/professional-avatar.png",
    role: "member",
  },
  {
    id: "4",
    name: "Taylor Smith",
    email: "taylor@company.com",
    avatar: "/professional-woman-smiling-avatar.png",
    role: "member",
  },
]

export const mockTasks: Task[] = [
  {
    id: "1",
    organizationId: "org-1",
    title: "Update Q4 sales projections",
    description: "Review and update the quarterly sales forecast based on current trends",
    status: "TODO",
    assignedBy: "1",
    owner: teamMembers[1],
    dueDate: "2025-12-01",
    confidence: "high",
    meetingId: "1",
    createdAt: "2025-11-25",
    approved: true,
  },
  {
    id: "2",
    organizationId: "org-1",
    title: "Prepare client presentation deck",
    description: "Create slides for the upcoming client meeting",
    status: "IN_PROGRESS",
    assignedBy: "1",
    owner: teamMembers[2],
    dueDate: "2025-11-29",
    confidence: "medium",
    meetingId: "1",
    createdAt: "2025-11-25",
    approved: true,
  },
  {
    id: "3",
    organizationId: "org-1",
    title: "Review marketing budget allocation",
    status: "IN_REVIEW",
    assignedBy: "1",
    owner: teamMembers[3],
    dueDate: "2025-11-30",
    confidence: "high",
    meetingId: "2",
    createdAt: "2025-11-24",
    approved: true,
  },
  {
    id: "4",
    organizationId: "org-1",
    title: "Schedule team retrospective",
    status: "COMPLETED",
    assignedBy: "1",
    owner: teamMembers[0],
    dueDate: "2025-11-26",
    confidence: "high",
    meetingId: "2",
    createdAt: "2025-11-24",
    approved: true,
  },
  {
    id: "5",
    organizationId: "org-1",
    title: "Draft product roadmap for 2026",
    description: "Outline key milestones and features for next year",
    status: "TODO",
    assignedBy: "1",
    owner: teamMembers[1],
    dueDate: "2025-12-05",
    confidence: "low",
    meetingId: "3",
    createdAt: "2025-11-26",
    approved: false,
  },
  {
    id: "6",
    organizationId: "org-1",
    title: "Coordinate with engineering on API updates",
    status: "IN_PROGRESS",
    assignedBy: "1",
    owner: teamMembers[2],
    dueDate: "2025-12-02",
    confidence: "medium",
    meetingId: "3",
    createdAt: "2025-11-26",
    approved: true,
  },
]

export const mockMeetings: Meeting[] = [
  {
    id: "1",
    organizationId: "org-1",
    title: "Weekly Team Standup",
    channelName: "meeting-1",
    status: "COMPLETED",
    createdBy: "1",
    startedAt: "2025-11-25T09:00:00Z",
    endedAt: "2025-11-25T09:30:00Z",
    participants: teamMembers.map(m => m.id),
    date: "2025-11-25",
    duration: 30,
    tasks: mockTasks.filter((t) => t.meetingId === "1"),
  },
  {
    id: "2",
    organizationId: "org-1",
    title: "Q4 Planning Session",
    channelName: "meeting-2",
    status: "COMPLETED",
    createdBy: "1",
    startedAt: "2025-11-24T14:00:00Z",
    endedAt: "2025-11-24T15:00:00Z",
    participants: ["1", "3", "4"],
    date: "2025-11-24",
    duration: 60,
    tasks: mockTasks.filter((t) => t.meetingId === "2"),
  },
  {
    id: "3",
    organizationId: "org-1",
    title: "Product Strategy Review",
    channelName: "meeting-3",
    status: "COMPLETED",
    createdBy: "1",
    startedAt: "2025-11-26T10:00:00Z",
    endedAt: "2025-11-26T10:45:00Z",
    participants: teamMembers.map(m => m.id),
    date: "2025-11-26",
    duration: 45,
    tasks: mockTasks.filter((t) => t.meetingId === "3"),
  },
]

export const mockTeamActivity: TeamActivity[] = [
  {
    id: "1",
    user: teamMembers[1],
    action: 'completed "Schedule team retrospective"',
    timestamp: "2 hours ago",
  },
  {
    id: "2",
    user: teamMembers[2],
    action: 'moved "Prepare client presentation" to In Progress',
    timestamp: "3 hours ago",
  },
  {
    id: "3",
    user: teamMembers[3],
    action: 'submitted "Review marketing budget" for review',
    timestamp: "5 hours ago",
  },
]

