export type UserRole = "manager" | "member"

export type TaskStatus = "todo" | "in-progress" | "review" | "done"

export type ConfidenceLevel = "high" | "medium" | "low"

export interface User {
  id: string
  name: string
  email: string
  avatar?: string
  role: UserRole
}

export interface Task {
  id: string
  organizationId: string
  meetingId?: string | null
  title: string
  description?: string | null
  assignedTo?: string | null
  assignedBy: string
  status?: "TODO" | "IN_PROGRESS" | "IN_REVIEW" | "COMPLETED" | "BLOCKED" | null
  priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | null
  dueDate?: string | null
  tags?: (string | null)[] | null
  autoGenerated?: boolean | null
  aiConfidence?: number | null
  tickets?: unknown
  createdAt?: string | null
  updatedAt?: string | null
  completedAt?: string | null
  // Relations (may be functions from Amplify)
  organization?: unknown
  meeting?: unknown
  // Legacy fields for compatibility
  owner?: User
  confidence?: ConfidenceLevel
  approved?: boolean
}

export interface Meeting {
  id: string
  organizationId: string
  title: string
  channelName: string
  status?: "SCHEDULED" | "LIVE" | "COMPLETED" | "CANCELLED" | null
  startedAt?: string | null
  endedAt?: string | null
  createdBy: string
  participants?: (string | null)[] | null
  recordingUrl?: string | null
  createdAt?: string | null
  updatedAt?: string | null
  // Relations (may be functions from Amplify)
  organization?: unknown
  transcripts?: unknown
  tasksCreated?: unknown
  // Legacy fields for compatibility
  date?: string
  duration?: number
  tasks?: Task[]
  transcript?: string
  isLive?: boolean
}

export interface Ticket {
  id: string
  organizationId: string
  taskId: string
  type?: "DEADLINE_EXTENSION" | "RESOURCE_REQUEST" | "CLARIFICATION" | "BLOCKER" | "OTHER" | null
  subject: string
  description: string
  createdBy: string
  assignedTo?: string | null
  status?: "OPEN" | "IN_REVIEW" | "RESOLVED" | "REJECTED" | null
  resolution?: string | null
  priority?: "LOW" | "MEDIUM" | "HIGH" | null
  createdAt?: string | null
  updatedAt?: string | null
  resolvedAt?: string | null
  // Relations (may be functions from Amplify)
  organization?: unknown
  task?: unknown
}

export interface TeamActivity {
  id: string
  user: User
  action: string
  timestamp: string
}

